services:
  - type: web
    name: django-chatbot
    runtime: docker
    repo: https://github.com/bmuia/bobGPT.git
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    healthCheckPath: /
    autoDeploy: true
